#!/bin/bash

# Set the name of the container that acts as the server
EC4DOCK_SERVERNAME=${EC4DOCK_SERVERNAME:-torqueserver}
EC4DOCK_WN_IMAGENAME=${EC4DOCK_WN_IMAGENAME:-torque:wn}

[ $# -ne 1 ] && echo "usage: $0 <nodenameid>" && exit 1
WN_NAME=$1

# Get the server IP address
EC4DOCK_SERVERIP=$(docker inspect -f '{{.NetworkSettings.IPAddress}}' $EC4DOCK_SERVERNAME)
[ $? -ne 0 ] && echo "could not get ip from server $EC4DOCK_SERVERNAME" && exit 1

# Create a new container
WN_CONTAINERNAME=$(docker run -h $WN_NAME --privileged -e "EC4DOCK_SERVERIP=$EC4DOCK_SERVERIP" -e "EC4DOCK_SERVERNAME=$EC4DOCK_SERVERNAME" --name $WN_NAME -id $EC4DOCK_WN_IMAGENAME)
[ $? -ne 0 ] && echo "could not create the new node $WN_NAME" && exit 1

# We get the IP address for the new node
WN_IPADDR=$(docker inspect -f '{{.NetworkSettings.IPAddress}}' $WN_CONTAINERNAME)
[ $? -ne 0 -o "$WN_IPADDR" == "" ] && echo "could not determine the IP address for the new node" && docker rm $(docker stop $WM_CONTAINERNAME) && exit 1

# Finally we add the node in the torque server
/opt/ec4docker/add-node $WN_NAME $WN_IPADDR
