#!/bin/bash
#
# EC4Docker - Elastic Cluster for Docker
# https://github.com/grycap/ec4docker
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# We are exporting the /home folder
cat >> /etc/exports << EOF
/home ${EC4DOCK_NODEBASENAME}*(rw,sync,no_subtree_check,fsid=0,no_root_squash)
EOF

# Now we start the daemos related to nfs
/etc/init.d/rpcbind restart
/etc/init.d/nfs-kernel-server restart

# If NFS failed to start, we exit failing
[ "$(cat /proc/filesystems | grep nfsd)" == "" ] && exit 1

exit 0