#!/bin/bash
#
# EC4Docker - Elastic Cluster for Docker
# https://github.com/grycap/ec4docker
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

NODENAME=$1
IPADDR=$2
CONTAINERNAME=$3

# We'll get the configuration if it exists
[ -f /etc/ec4docker/ec4docker.conf ] && source /etc/ec4docker/ec4docker.conf
DOCKERCMD=docker
[ "$EC4DOCK_DOCKER_NODE" != "" ] &&  DOCKERCMD="docker -H $EC4DOCK_DOCKER_NODE"

$DOCKERCMD cp /etc/munge/munge.key $CONTAINERNAME:/etc/munge/munge.key 2> /dev/null > /dev/null
[ $? -ne 0 ] && echo "error staging in the munge keyfile" && exit 1

$DOCKERCMD cp /usr/local/etc/slurm.conf $CONTAINERNAME:/usr/local/etc/slurm.conf 2> /dev/null > /dev/null
[ $? -ne 0 ] && echo "error staging in the slurm config file" && exit 1

exit 0
