#!/bin/bash
#
# EC4Docker - Elastic Cluster for Docker
# https://github.com/grycap/ec4docker
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export EC4DOCK_SERVERNAME=${EC4DOCK_SERVERNAME:-torqueserver}
export EC4DOCK_MAXNODES=${EC4DOCK_MAXNODES:-4}
export EC4DOCK_NODEBASENAME=${EC4DOCK_NODEBASENAME:-ec4docknode}
export EC4DOCK_SERVERIP=${EC4DOCK_SERVERIP:-127.0.0.1}

mkdir /etc/ec4docker
cat > /etc/ec4docker/ec4docker.conf << EOF
EC4DOCK_SERVERNAME=$EC4DOCK_SERVERNAME
EC4DOCK_MAXNODES=$EC4DOCK_MAXNODES
EC4DOCK_NODEBASENAME=$EC4DOCK_NODEBASENAME
EC4DOCK_WN_IMAGENAME=$EC4DOCK_WN_IMAGENAME
EC4DOCK_FRONTEND_IMAGENAME=$EC4DOCK_FRONTEND_IMAGENAME
EC4DOCK_SERVERIP=$EC4DOCK_SERVERIP
EC4DOCK_DOCKER_NODE=$EC4DOCK_DOCKER_NODE
EC4DOCK_DOCKER_NETWORK=$EC4DOCK_DOCKER_NETWORK
EOF

sleep 5