#!/bin/bash

# We know the path of the default installation of torque
TORQUE_PATH=/var/spool/torque

# We tell torque which is the server name
echo $EC4DOCK_SERVERNAME > /etc/torque/server_name

# And also set the IP for the server name
echo "$EC4DOCK_SERVERIP $EC4DOCK_SERVERNAME" >> /etc/hosts

# Now we'll configure MOM
cat > ${TORQUE_PATH}/mom_priv/config << EOF
\$clienthost $EC4DOCK_SERVERNAME
\$max_conn_timeout_micro_sec 10000
\$mom_host $(hostname)
\$status_update_time 30
EOF

# Finally, let's restart the services
while [ "$(pgrep pbs_mom)" != "" ]; do
        service torque-mom stop
        sleep 3
done

while [ "$(pgrep pbs_mom)" == "" ]; do
        service torque-mom start
        sleep 3
done
