#!/bin/bash
#
# EC4Docker - Elastic Cluster for Docker
# https://github.com/grycap/ec4docker
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# We know the path of the default installation of torque
TORQUE_PATH=/var/spool/torque

# We tell torque which is the server name
echo $EC4DOCK_SERVERNAME > /etc/torque/server_name

# And also set the IP for the server name
echo "$EC4DOCK_SERVERIP $EC4DOCK_SERVERNAME" >> /etc/hosts

# Now we'll configure MOM
cat > ${TORQUE_PATH}/mom_priv/config << EOF
\$clienthost $EC4DOCK_SERVERNAME
\$max_conn_timeout_micro_sec 10000
\$mom_host $(hostname)
\$status_update_time 30
EOF

# Finally, let's restart the services
while [ "$(pgrep pbs_mom)" != "" ]; do
        service torque-mom stop
        sleep 3
done

while [ "$(pgrep pbs_mom)" == "" ]; do
        service torque-mom start
        sleep 3
done
exit 0